"""
Django settings for gofresh project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import datetime

DEBUG = False

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!u1k((sc(vihdo=4m0+c4ze&1h4rylgn$ftmae4+)mmsp8sx42'

# SECURITY WARNING: don't run with debug turned on in production!

AUTH_USER_MODEL = 'accounts.AuthUser'

#RUNNING_HOST = '127.0.0.1'
#RUNNING_HOST = 'www.fanvault.yukti.io/'


def get_running_host():
    if DEBUG is True:
        return '127.0.0.1'
    return '54.67.89.9'

# used for smart_selects
# USE_DJANGO_JQUERY = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'smart_selects',
    'crispy_forms',
    'django_filters',
    'stores',
    'products',
    'accounts',
    'orders',
    'geoposition',
    'django_object_actions',
    'mathfilters',
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}


SENDGRID_API_KEY = 'SG.8H-dxdnxTpaw4xnMqiSFKw.FMFjuGp48USx4SWnNWMoBhkqEuU1uhkPgO2noNwHge4'
SENDGRID_SENDER = 'ashiqul@ergo-ventures.com'
#EMAIL_BACKEND = "sgbackend.SendGridBackend"



EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'gofreshdir'
EMAIL_HOST_PASSWORD = 'gofresh123'
EMAIL_PORT = 587


from django.contrib import admin
admin.site.site_header = 'GoFresh Adminstration'


ADMINS = [('ergoguy', 'ergodev299@gmail.com')]

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gofresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gofresh.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [

    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
]

GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyC7RuSkF7AJ87HY_T8DmL61FRp4d-FJIeg'

GEOPOSITION_MAP_OPTIONS = {
    'minZoom': 3,
    'maxZoom': 20,
}

GEOPOSITION_MARKER_OPTIONS = {
    'cursor': 'move'
}

GEOPOSITION_MAP_WIDGET_HEIGHT = 400

#NEAREST_STORE_LIMIT = 3

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#celery settings

CELERY_BROKER_URL = 'amqp://gofresh:ergoventures@localhost:5672/gofresh_vhost'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'staticfiles'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/gofresh_cache',
    }
}
