# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_access_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fb_uid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_logged_in_from_fb',
            field=models.BooleanField(default=False),
        ),
    ]
