# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 09:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160921_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_optional',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999' '+880155456509'. Up to 15 digits allowed.", regex='^\\+?\\(?\\d{2,4}\\)?[\\d\\s-]{3,15}$')]),
        ),
    ]
