# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title_address', models.CharField(blank=True, max_length=1000)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('opening_time', models.TimeField(choices=[(datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(21, 0), '9:00 pm')], default=datetime.time(8, 0))),
                ('closing_time', models.TimeField(choices=[(datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(21, 0), '9:00 pm')], default=datetime.time(20, 0))),
                ('last_order_receiving_time', models.TimeField(choices=[(datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(21, 0), '9:00 pm')], default=datetime.time(20, 0))),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('area', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_area', to='stores.Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_city', to='stores.City')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='stores.City'),
        ),
    ]
