# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 18:37
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
        migrations.AddField(
            model_name='store',
            name='position',
            field=geoposition.fields.GeopositionField(default='23.762880,90.386667', max_length=42),
            preserve_default=False,
        ),
    ]
