# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20160917_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=stores.models.store_upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='store',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
