# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 12:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20160910_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=1000)),
                ('road_no', models.CharField(blank=True, max_length=1000)),
                ('house_no', models.CharField(blank=True, max_length=1000)),
                ('floor_no', models.CharField(blank=True, max_length=1000)),
                ('address_detail', models.CharField(blank=True, max_length=1000)),
                ('product_receiver_name', models.CharField(max_length=1000)),
                ('product_receiver_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999' '+880155456509'. Up to 15 digits allowed.", regex='^\\+?\\(?\\d{2,4}\\)?[\\d\\s-]{3,15}$')])),
                ('product_receiver_phone_optional', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999' '+880155456509'. Up to 15 digits allowed.", regex='^\\+?\\(?\\d{2,4}\\)?[\\d\\s-]{3,15}$')])),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.IntegerField(choices=[(1, '8AM - 12PM'), (2, '12PM - 4PM'), (3, '4PM - 10PM')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Delivered')], default=1)),
                ('invoice_number', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DeliveryInformation')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
