# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_information', to='orders.DeliveryInformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user_profile', to='accounts.UserProfile'),
        ),
    ]
