# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160910_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinformation',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='deliveryinformation',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(1, '8AM - 12PM'), (2, '12PM - 4PM'), (3, '4PM - 10PM')], default=1),
        ),
    ]
