# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160911_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinformation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
    ]
