# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20160914_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
