# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20160915_1949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinorder',
            unique_together=set([]),
        ),
    ]
