# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
