# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20161216_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='media/category/default.png', height_field='height_field', null=True, upload_to=products.models.category_upload_location, width_field='width_field'),
        ),
    ]
